name: EpicHoppers
description: EpicHoppers
main: com.songoda.epichoppers.EpicHoppersPlugin
depend: [Arconix]
softdepend: [WildStacker, Towny, RedProtect, Kingdoms, PlotsSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, Vault]
version: 3.1
author: Songoda
commands:
  epichoppers:
    description: View information on this plugin.
    default: true
    aliases: [eh]
    usage: /eh